tmpl = {
    'BLOCK_STONE': {
        'token': 'BLOCK_STONE',
        'glyph': ord('#'),
        'ispass': False,
        'isliquid': False,
        'istransparent': False},
    'BLOCK_AIR': {
        'token': 'BLOCK_AIR',
        'glyph': ord('.'),
        'ispass': True,
        'isliquid': False,
        'istransparent': True},
    'BLOCK_GLASS': {
        'token': 'BLOCK_GLASS',
        'glyph': ord('"'),
        'ispass': False,
        'isliquid': False,
        'istransparent': True},
    'DOORWAY_SECRET': {
        'token': 'DOORWAY_SECRET',
        'glyph': ord('#'),
        'ispass': True,
        'isliquid': False,
        'istransparent': False}}
