tmpl = {
    'FIRE_ELEMENTAL': {
        'glyph': ord('E'),
        'classname': 'AiCreature',
        'invsize': 0},
    'RABBIT': {
        'glyph': ord('r'),
        'classname': 'AiCreature',
        'invsize': 0},
    'NORTH_GOING_ZAX': {
        'glyph': ord('Z'),
        'classname': 'NorthGoingZax',
        'invsize': 0},
    'PLAYER_CHASER': {
        'glyph': ord('C'),
        'classname': 'PlayerChaser',
        'invsize': 0},
    'PICKUP_DROPPER': {
        'glyph': ord('P'),
        'classname': 'PickupDropper',
        'invsize': 2},
    'TRACK_AND_ATTACK': {
        'glyph': ord('A'),
        'classname': 'TrackAndAttack',
        'invsize': 2}}
